name: "Staging env provision & configure"
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  provision_and_configure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_S3_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_TF_STATE_S3_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        if: github.event_name == 'pull_request'
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Get ec2 public ip
        id: ec2_ip
        if: steps.apply.outcome == 'success'
        env:
          TF_LOG: ""
        run: |
          echo "Raw Terraform output:"
          EC2_PUBLIC_IP=$(terraform output -raw staging_public_ip | tr -d '\n' | cut -d ':' -f 1)

      - name: Configure ec2 instance
        id: configure_ec2
        if: steps.ec2_ip.outcome == 'success' && false
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ENV_VARIABLES: ${{ secrets.ENV }}
        run: |
          EC2_PUBLIC_IP=$(terraform output -raw staging_public_ip | cut -d ':' -f 1)
          echo "$EC2_PUBLIC_IP"

          # Add SSH key to the SSH agent
          mkdir ~/.ssh/
          echo "${SSH_KEY}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh-keyscan -H $EC2_PUBLIC_IP > ~/.ssh/known_hosts

          ssh -i ec2_key.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
            # Update & Upgrade
            sudo apt update -y && sudo apt upgrade -y

            # Install Node.js
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Install pm2
            sudo npm install pm2 -g

            # Clone the repository
            mkdir -p ~/app && cd ~/app
            git clone https://github.com/hasangawr/PlanCraftr.git .
            cd backend

            # Set up environment and install dependencies
            echo "$ENV_VARIABLES" > .env
            npm install
            npm run build

            # Start the app using pm2
            pm2 start "npm run start"

            # Install Caddy for reverse proxy
            sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
            sudo apt update
            sudo apt install -y caddy

            # Configure Caddy reverse proxy
            echo "api.plancraftr.com {
              reverse_proxy localhost:3000
            }" | sudo tee Caddyfile

            # Start Caddy
            sudo systemctl restart caddy
          EOF
